# Rolebinding for the argo-workflow service account to the artifactgc role (see
# gc-role.yaml).
# For more information about rolebindings, see
# https://kubernetes.io/docs/reference/access-authn-authz/rbac/#rolebinding-example
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gc-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: argo-workflow
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: artifactgc
  apiGroup: rbac.authorization.k8s.io
