{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ogdc.fullname" . }}-ingress
  labels:
    {{- include "ogdc.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
      - {{ .Values.ogdc_public_host | quote }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.ogdc_public_host | quote }}
    http:
      paths:
      - path: /ogdc/api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ogdc-service-service
            port:
              number: 8000
      # TODO: this will need some re-thinking based on how we deal with
      # https://github.com/QGreenland-Net/ogdc-helm/issues/46. 
      - path: /ogdc/storage(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: qgnet-ogdc-minio
            port:
              number: 9000
{{- end }}
