{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  - host: {{ .Values.ogdc_public_host | quote }}
    http:
      paths:
      - path: {{ .Values.ingress.apiPath | quote }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 8000
      # TODO: this will need some re-thinking based on how we deal with
      # https://github.com/QGreenland-Net/ogdc-helm/issues/46.
      - path: {{ .Values.ingress.storagePath | quote }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-minio
            port:
              number: 9000
{{- end }}
