apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-minio-pvc
  namespace: qgnet
spec:
  accessModes:
    {{- toYaml (index .Values.minio.persistence .Values.env).accessModes | nindent 4 }}
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ (index .Values.minio.persistence .Values.env).storageClassName | quote }}