apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-minio-pvc
  namespace: {{ .Values.OgdcNamespace }}
spec:
  accessModes:
    {{- $env := .Values.env | default "dev" -}}
    {{- toYaml (index .Values.minio.persistence .Values.env).accessModes | nindent 4 }}
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ (index .Values.minio.persistence .Values.env).storageClassName | quote }}