{{ if eq .Values.env "dev" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: {{ .Values.OgdcNamespace }}
spec:
  capacity:
    storage: 10Gi  # Adjust size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.MinioPVHostPath }}
{{ end }}
