{{- $env := .Values.env | default "dev" -}}
{{- $postgrespvc := index (index (index .Values "argo-workflows" "postgresql" "primary" "persistence") $env) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgresql-pvc
  namespace: {{ .Values.OgdcNamespace }}
spec:
  accessModes:
{{ toYaml $postgrespvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ $postgrespvc.storageClassName | quote }}