apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-credentials
  namespace: {{ .Values.OgdcNamespace }}
type: Opaque
stringData:
  root-user: "admin"
  root-password: "your-secret-password"

