apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-credentials
  namespace: {{ .Values.OgdcNamespace }}
type: Opaque
stringData:
  rootUser: "admin"
  rootPassword: "your-secret-password"
