apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-credentials
  namespace: {{ .Values.OgdcNamespace }}
type: Opaque
stringData:
  root-user: "admin"
  root-password: "your-secret-password"

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-credentials
  namespace: {{ .Values.OgdcNamespace }}
type: Opaque
stringData:
  postgres-username: "postgres"
  postgres-password: "your-secret-password"
  username: "postgres"
  password: "your-secret-password"
