apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-workflow-pvc
  namespace: qgnet
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # Match this to your PV's storage
  {{ if eq .Values.env "dev" }}
  storageClassName: ""
  {{ else }}
  storageClassName: "csi-cephfs-sc"
  {{ end }}