apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-workflow-pvc
  namespace: {{ .Values.OgdcNamespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # Match this to your PV's storage
  storageClassName: {{ (index .Values.global .Values.env).defaultStorageClass | quote }}