{{ if eq .Values.ENV "dev" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-workflow-pv
  namespace: qgnet
spec:
  capacity:
    storage: 5Gi  # Adjust size as needed
  accessModes:
    - ReadWriteMany  # Allows multiple nodes to write
  hostPath:
    path: {{ .Values.OgdcPVHostPath }}
{{ end }}
