## override values.yaml with values to use for running on the NCEAS dev cluster
##
## example:
##
##  export RELEASE_NAME=qgnet-ogdc NAMESPACE=qgnet
##  envsubst < ./helm/examples/values-dev-cluster-ogdc-example.yaml | \
##  helm upgrade --install "$RELEASE_NAME" --debug -n "$NAMESPACE" \
##      -f - oci://ghcr.io/qgreenland-net/charts/ogdc
##
## (or to install from local helm chart code, replace:
##  oci://ghcr.io/qgreenland-net/charts/ogdc --version [version]
##  with: ./helm)
##
## see values.yaml for full documentation on the following parameters
##


global:
  ## @param global.passwordsSecret The name of the Secret containing application passwords
  ## This is the secret deployed using your own private, edited version of `../admin/secrets.yaml`.
  ##
  ## (Note the actual key passwordsSecret is not used anywhere; only the yaml anchor/alias
  ##  &passwordSecretName. IF YOU OVERRIDE THIS VALUE IN ANOTHER VALUES-OVERLAY FILE, YOU ALSO
  ## NEED TO OVERRIDE THE VALUES THAT USE THIS ANCHOR - search this file for 'passwordSecretName')
  passwordsSecret: &passwordSecretName ${RELEASE_NAME}-secrets

## argo-workflows configuration
## See https://argoproj.github.io/argo-workflows/
argo-workflows:

  crds:
    install: false

  singleNamespace: true

  controller:
    workflowNamespaces:
      - ${NAMESPACE}

    persistence:
      postgresql:
        host: "${RELEASE_NAME}-db-cnpg-rw"
        database: "ogdc"
        tableName: "argo_workflows_archive"
        userNameSecret:
          name: "${RELEASE_NAME}-db-postgres-secrets"
          key: "username"
        passwordSecret:
          name: "${RELEASE_NAME}-db-postgres-secrets"
          key: "password"

  ## Argo Server configuration
  server:

    ## Ingress configuration.
    # ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
    ingress:
      ## -- Enable an ingress resource
      ## Enable an ingress resource for the Argo server
      enabled: false

  ## Artifact repository configuration
  artifactRepository:
    s3:
      ## Note the `key` attribute is not the actual secret, it's the PATH to
      ## the contents in the associated secret, as defined by the `name` attribute.
      accessKeySecret:
        name: *passwordSecretName
        key: rootUser
      secretKeySecret:
        name: *passwordSecretName
        key: rootPassword


## MinIO configuration
minio:
  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    enabled: true

    ## A manually managed Persistent Volume and Claim
    ## Requires persistence.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    existingClaim: "cephfs-${RELEASE_NAME}-minio-pvc"

  existingSecret: *passwordSecretName

# Ensures that local image of ogdc-service is used.
image:
  repository: "ghcr.io/qgreenland-net/ogdc-runner"
  tag: latest
  pullPolicy: Always

# Ingress configuration
ingress:
  enabled: true
  tls:
    - hosts:
        - ogdc.test.dataone.org
      secretName: ogdc-tls-cert

environment: "dev"

auth:
  accessMode: "authenticated"
  oidcSecretName: "${RELEASE_NAME}-oidc-config"

ogdc_public_host: "ogdc.test.dataone.org"
ogdc_s3_endpoint: "http://${RELEASE_NAME}-minio:9000"
ogdc_public_s3_url: "https://ogdc.test.dataone.org/storage"
ogdc_workflow_pvc_name: "cephfs-${RELEASE_NAME}-workflow-pvc"
ogdc_input_pvcs:
  - claimName: "cephfs-${RELEASE_NAME}-adc-tiles-pvc"
    description: "ADC Tile Store PVC"
ogdc_viz_workflow_image: "ghcr.io/permafrostdiscoverygateway/viz-workflow:latest"
