## override values.yaml with values to use for running on the NCEAS prod cluster
##
## example:
##
##  helm upgrade --install ogdc --debug -n qgnet \
##                          -f ./helm/examples/values-prod-cluster-ogdc-example.yaml \
##                          oci://ghcr.io/qgreenland-net/charts/ogdc --version [version]
##
## (or to install from local helm chart code, replace:
##  oci://ghcr.io/qgreenland-net/charts/ogdc --version [version]
##  with: ./helm)
##
## see values.yaml for full documentation on the following parameters
##


global:
  ## @param global.passwordsSecret The name of the Secret containing application passwords
  ## This is the secret deployed using your own private, edited version of `../admin/secrets.yaml`.
  ##
  ## (Note the actual key passwordsSecret is not used anywhere; only the yaml anchor/alias
  ##  &passwordSecretName. IF YOU OVERRIDE THIS VALUE IN ANOTHER VALUES-OVERLAY FILE, YOU ALSO
  ## NEED TO OVERRIDE THE VALUES THAT USE THIS ANCHOR - search this file for 'passwordSecretName')
  ##
  ## IMPORTANT NOTE: make sure you edit this, since IT INCLUDES THE RELEASE NAME! For
  ## example, if the release name is 'myrelease', the value of name: would be
  ## 'myrelease-secrets'.
  ##
  passwordsSecret: &passwordSecretName qgnet-ogdc-secrets

## argo-workflows configuration
## See https://argoproj.github.io/argo-workflows/
argo-workflows:

  ## Custom resource configuration
  crds:
    ## -- Install and upgrade CRDs
    install: false

  ## Artifact repository configuration## Artifact repository configuration
  artifactRepository:
    s3:
      ## Note the `key` attribute is not the actual secret, it's the PATH to
      ## the contents in the associated secret, as defined by the `name` attribute.
      accessKeySecret:
        name: *passwordSecretName
        key: rootUser
      secretKeySecret:
        name: *passwordSecretName
        key: rootPassword


## MinIO configuration
minio:
  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    enabled: true

    ## A manually managed Persistent Volume and Claim
    ## Requires persistence.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    existingClaim: "cephfs-qgnet-ogdc-minio-pvc"

  existingSecret: *passwordSecretName

image:
  repository: "ghcr.io/qgreenland-net/ogdc-runner"
  tag: latest

environment: "prod"

ogdc_public_host: "api.dataone.org"
internal_s3_endpoint_url: "http://qgnet-ogdc-minio:9000"
public_s3_endpoint_url: "https://api.dataone.org/ogdc/storage/"
dataone_node_url: "https://arcticdata.io/metacat/d1/mn"

ingress:
  enabled: true
