# Creates a persistent volume claim for use by workflow
#
# This should be done only one time, separately from the helm install/upgrade cycle
#
# Update the RELEASE_NAME and NAMESPACE variables below to match your release name, using envsubst or
# manually replacing ${RELEASE_NAME} and ${NAMESPACE} with your release name and namespace.
#
# NOTE: ensure that a PersistentVolume has already been created before creating
#       the PersistentVolumeClaim!
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  ## See https://github.com/DataONEorg/k8s-cluster/blob/main/storage/storage.md#dataone-volume-naming-conventions
  ## cephs-{release}-{function}-{instance}, where {release} usually = {namespace}
  #
  ## Use your own release name
  name: cephfs-${RELEASE_NAME}-workflow-pvc
  ## Use your own namespace
  namespace: ${NAMESPACE}
  labels:
    velero.io/exclude-from-backup: "true"
spec:
  ## See https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteMany
  ## Use your own storage class
  storageClassName: csi-cephfs-sc-ephemeral
  resources:
    requests:
      storage: 100Gi