
######################################################################################
#     D O   N O T   C H E C K   C R E D E N T I A L S   I N T O   G I T H U B ! ! !
######################################################################################
#
# Edit this file to add your passwords, then install them in your cluster. 
# $ RELEASE_NAME=<your-release-name> envsubst < helm/admin/postgres-secrets.yaml | \
#       kubectl apply -n "$NAMESPACE" -f -
apiVersion: v1
kind: Secret
metadata:
  name: ${RELEASE_NAME}-db-postgres-secrets

type: kubernetes.io/basic-auth
stringData:
  username: admin # required field for kubernetes.io/basic-auth
  password: password # required field for kubernetes.io/basic-auth
