name: "Build and publish ogdc-helm chart"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

env:
  FORCE_COLOR: 3
  CHART_NAME: "ogdc"
  REGISTRY: "ghcr.io"

jobs:
  #######################################################################
  # Build & Test Helm Chart
  #######################################################################
  build-helm:
    name: "Build and test Helm chart"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v5"
        with:
          fetch-depth: 0

      - name: "Verify Helm is available"
        run: |
          helm version

      - name: "Helm dependency update"
        run: |
          cd helm
          helm dependency update

      - name: "Lint Helm chart"
        run: |
          helm lint helm/

      - name: "Template Helm chart"
        run: |
          helm template test helm/ --debug

      - name: "Package Helm chart"
        run: |
          helm package helm/ --destination .

      - name: "Upload chart package as artifact"
        uses: "actions/upload-artifact@v4"
        with:
          name: "helm-chart"
          path: "*.tgz"

  #######################################################################
  # Publish Helm Chart to GHCR
  #######################################################################
  publish-helm:
    # Only push on tag or push to main.
    if: github.ref_type == 'tag' || github.ref == 'refs/heads/main'
    name: "Push Helm chart to GHCR"
    runs-on: "ubuntu-latest"
    needs: ["build-helm"]
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v5"

      - name: "Set up Helm"
        uses: "azure/setup-helm@v4"
        with:
          version: "latest"

      - name: "Download chart package"
        uses: "actions/download-artifact@v4"
        with:
          name: "helm-chart"

      - name: "Set CHART_VERSION environment variable"
        run: |
          CHART_VERSION=$(grep '^version:' helm/Chart.yaml | awk '{print $2}')
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV

      - name: "GHCR Login"
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: "Push Helm chart to GHCR"
        run: |
          CHART_PACKAGE="${{ env.CHART_NAME }}-${{ env.CHART_VERSION }}.tgz"
          
          # Push to GHCR
          helm push "${CHART_PACKAGE}" oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts
          
          echo "✅ Successfully pushed ${CHART_PACKAGE} to ${{ env.REGISTRY }}/${{ github.repository_owner }}/charts"

      - name: "Generate installation instructions"
        run: |
          cat << EOF >> $GITHUB_STEP_SUMMARY
          ## 📦 Helm Chart Published
          
          **Chart:** ${{ env.CHART_NAME }}
          **Version:** ${{ env.CHART_VERSION }}
          **Registry:** oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts/${{ env.CHART_NAME }}
          
          ### Installation
          
          \`\`\`bash
          helm upgrade --install ${{ env.CHART_NAME }} \\
            oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts/${{ env.CHART_NAME }} \\
            --version ${{ env.CHART_VERSION }} \\
            -n qgnet --create-namespace
          \`\`\`
          
          ### With values file
          
          \`\`\`bash
          helm upgrade --install ${{ env.CHART_NAME }} \\
            oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts/${{ env.CHART_NAME }} \\
            --version ${{ env.CHART_VERSION }} \\
            -f values-dev-cluster-ogdc.yaml \\
            -n qgnet
          \`\`\`
          EOF

  #######################################################################
  # GitHub release
  #######################################################################
  publish-gh-release:
    # Only publish a GH release when publish-helm task is complete
    # and the ref type is a tag (e.g., v0.1.0).
    if: github.ref_type == 'tag'
    name: "Create GitHub release"
    needs: ["publish-helm"]
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"

      - name: "Download chart package"
        uses: "actions/download-artifact@v4"
        with:
          name: "helm-chart"

      - name: "Release"
        uses: "softprops/action-gh-release@v2"
        with:
          generate_release_notes: true
          files: "*.tgz"
